local Match = require("cmp_kitty.match")
local dut = Match.new()

describe("ip", function()
	it("should match ip addresses", function()
		assert.is_true(dut:ip("1.1.1.1"))
		assert.is_true(dut:ip("12.12.12.12"))
		assert.is_true(dut:ip("123.123.123.123"))
	end)

	it("should not match numbers", function()
		assert.is_false(dut:ip("123"))
		assert.is_false(dut:ip("123.123"))
	end)
end)
