local Completions = require("cmp_kitty.completions")

describe("add", function()
	local dut = Completions.new()
	dut:set_item_lifetime(60)

	it("should start empty", function()
		assert.equal(0, dut:len())
	end)

	it("should add item", function()
		dut:add({ label = "a" })
		assert.is_true(dut:contains("a"))
		assert.equal(1, dut:len())
	end)

	it("should add each item only once", function()
		dut:add({ label = "a" })
		dut:add({ label = "a" })
		dut:add({ label = "a" })
		assert.is_true(dut:contains("a"))
		assert.equal(1, dut:len())
	end)

	it("should add multiple items", function()
		dut:add({ label = "a" })
		dut:add({ label = "b" })
		dut:add({ label = "c" })
		assert.equal(3, dut:len())
	end)
end)
